line-length = 500

[lint]
select = [
    "E",  # pycodestyle error
    "W",  # pycodestyle warning
    "F",  # Pyflakes
    "B",  # bugbear
    "UP",  # pyupgrade
    "N",  # pep8-naming
    "I001",  # isort
    "Q000",  # flake8-quotes
]
ignore-init-module-imports = true
ignore = [
    "E402",
    "E722"
]

[lint.flake8-quotes]
inline-quotes = "single"
